### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

### ISSUE THREAD

**Issue by yspreen** [ankurk91/vue-toast-notification#64] opened 2021-12-12 21:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 3.2.22
* Browser name and version : Chrome 96
* This package version : 2.0.1

**Current behavior**
Whenever I call `this.$toast.open('.');` I get:

```
runtime-core.esm-bundler.js?5c40:6769 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at patchAttr (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:473:16)
    at patchProp (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:672:9)
    at mountElement (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3946:25)
    at processElement (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3918:13)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3838:21)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4377:21)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:195:29)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4496:9)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4279:9)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4237:17)
logError @ runtime-core.esm-bundler.js?5c40:6769
handleError @ runtime-core.esm-bundler.js?5c40:6755
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:6709
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?5c40:6715
invoker @ runtime-dom.esm-bundler.js?830f:350
```

**Minimal reproduction of the problem with instructions**

I just followed the instructions. I have the line above to show the toast and `createApp(App).use(router).use(VueToast).mount('#app');` in main.ts

using class components and hammer but no other libs

**Comment by yspreen** [comment] 2021-12-12 21:07
also copying the example exactly and trying to use app.$toast in a component doesn't really seem to work. it's undefined. this.$toast exists and has the right types but then I get this error

**Comment by ankurk91** [comment] 2021-12-13 07:19
The error does not seems to be coming from vue-toast component, can you share a minimal reproduction on codesandbox?

**Comment by ankurk91** [comment] 2021-12-19 06:53
closing due to lack of info

**Closed by ankurk91** 2021-12-19 06:53 UTC
Labels: need-more-info

**Comment by misteryomi** [comment] 2021-12-30 15:38
@yspreen 

Use it this way:

```
this.$toast.open({
    message: 'Something went wrong!',
    type: 'error', //specify `success` or `error` here
    // all of other options may go here
});
```

**Comment by yspreen** [comment] 2022-01-03 21:50
@misteryomi thank you!

for some reason I expected the call to work like other js libraries where the first param is required (text) and the next one is the options dict. of course, I had to wrap the message in an object instead and pass everything at once. thanks again

**Comment by yspreen** [comment] 2022-01-03 21:53
ahh wait, there is actually an overload that accepts just a string. that one doesn't work for me 🤔

**Comment by victor-ponamariov** [comment] 2022-01-24 10:04
This doesn't work for me: 

```this.$toast.open('You did it!');```

 with the same exception

This works
```
this.$toast.open({
    message: 'Something went wrong!',
    type: 'error', //specify `success` or `error` here
    // all of other options may go here
});```
